[package]
name = "photo-booth-v2"
version = "2.3.1"
edition = "2024"

[dependencies]
nokhwa = { git = "https://github.com/l1npengtul/nokhwa.git", branch = "0.10", features = [
  "input-native",
  "output-threaded",
], optional = true }
iced = { version = "0.14.0", features = [
  "tokio",
  "image",
  "qr_code",
  "svg",
  "lazy",
  "advanced",
] }
image = "0.25.2"
serde = "1.0.210"
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
gphoto2 = { version = "3.3.1", optional = true }
reqwest = { version = "0.12.9", features = [
  "json",
  "multipart",
  "stream",
], optional = true }
gcp_auth = { version = "0.12.3", optional = true }
chrono = "0.4.38"
dotenv_codegen = "0.15.0"
bytes = "1.8.0"
lyon_algorithms = "1.0.4"
once_cell = "1.20.2"
log = "0.4.27"
env_logger = "0.11.8"
regex = "1.11.1"
async-trait = "0.1.89"
anyhow = "1.0.101"
futures = "0.3.31"
hex_color = { version = "3.0.0", features = ["serde"] }
clap = { version = "4.5.58", features = ["derive"] }
cups_rs = { version = "0.3.0", optional = true }

[features]
default = [
  "camera_nokhwa",
  "camera_gphoto2",
  "storage_google_drive",
  "storage_local_filesystem",
  "email_gapps_script_webhook",
  "renderer_simple",
  "printer_cups",
  "mock",
]
fast_animations = [] # faster animations to speed up iteraction during dev
mock = []
camera_nokhwa = ["dep:nokhwa"]
camera_gphoto2 = ["dep:gphoto2"]
storage_google_drive = ["dep:gcp_auth", "dep:reqwest"]
storage_local_filesystem = []
email_gapps_script_webhook = ["storage_google_drive", "dep:reqwest"]
renderer_simple = []
printer_cups = ["dep:cups_rs"]

# The following lines from https://bevyengine.org/learn/quick-start/getting-started/setup/
# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
