name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test (x86_64 Linux)
    runs-on: ubuntu-24.04
    permissions:
      id-token: "write"
      contents: "read"

    steps:
      - uses: actions/checkout@v7

      - uses: DeterminateSystems/nix-installer-action@v22

      - uses: DeterminateSystems/magic-nix-cache-action@v14

      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: nix develop --command cargo test --locked --features mock
